Added option for parameters in various OMR build scripts
If a specific repo, branch or label is provided, then the
script will use it. Otherwise these values default to the
values that already existed in the script. Additionally
the script will check if ccache is installed on the machine
before running the ccache command, so the job won't fail
on machines that don't have ccache (e.g. docker containers).
[skip ci]

Signed-off-by: Colton Mills <millscolt3@gmail.com>

diff --git a/buildenv/jenkins/jobs/builds/Build-linux_aarch64 b/buildenv/jenkins/jobs/builds/Build-linux_aarch64
--- a/buildenv/jenkins/jobs/builds/Build-linux_aarch64
+++ b/buildenv/jenkins/jobs/builds/Build-linux_aarch64
@@ -11,8 +11,12 @@ def setBuildStatus(String message, String state, String sha) {
     ]);
 }
 
+LABEL = (params.LABEL) ? "${params.LABEL}" : "Linux && x86 && compile:aarch64"
+REPO = (params.OMR_REPO) ? "${params.OMR_REPO}" : "https://github.com/eclipse/omr.git"
+BRANCH = (params.OMR_BRANCH) ? "${params.OMR_BRANCH}" : ((params.MERGE_COMMIT) ? "${MERGE_COMMIT}" : "refs/heads/master")
+
 pipeline {
-    agent{label 'Linux && x86 && compile:aarch64'}
+    agent{label "${LABEL}"}
     environment {
         PATH = "/usr/lib/ccache/:/home/jenkins/aarch64/toolchain/bin:$PATH"
         PLATFORM = "aarch64-linux-gcc"
@@ -22,9 +26,12 @@ pipeline {
         stage('Get Sources') {
             steps {
                 timestamps {
-                    checkout([$class: 'GitSCM', branches: [[name: '${MERGE_COMMIT}']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/eclipse/omr.git']]])
-                    
-                    setBuildStatus("In Progress","PENDING","${MERGE_COMMIT}")
+                    checkout([$class: 'GitSCM', branches: [[name: "${BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "${REPO}"]]])
+                    script {
+                        if(params.MERGE_COMMIT){
+                            setBuildStatus("In Progress","PENDING","${MERGE_COMMIT}")
+                        }
+                    }
                 }
             }
         }
@@ -32,7 +39,7 @@ pipeline {
             steps {
                 timestamps {
                     echo 'Output CCACHE stats before running and clear them'
-                    sh '''ccache -s -z'''
+                    sh '''(ccache --version &>/dev/null && ccache -s -z) || echo "Warning: ccache not found"'''
                     
                     echo 'Configure...'
                     sh '''make -f run_configure.mk OMRGLUE=./example/glue SPEC=linux_aarch64'''
@@ -41,7 +48,7 @@ pipeline {
                     sh '''make -j4'''
                     
                     echo 'Output CCACHE stats after running'
-                    sh '''ccache -s'''
+                    sh '''(ccache --version &>/dev/null && ccache -s) || echo "Warning: ccache not found"'''
                 }
             }
         }
@@ -55,10 +62,18 @@ pipeline {
     }
     post {
         success {
-            setBuildStatus("Complete","SUCCESS","${MERGE_COMMIT}")
+            script {
+                if(params.MERGE_COMMIT){
+                    setBuildStatus("Complete","SUCCESS","${MERGE_COMMIT}")
+                }
+            }
         }
         failure {
-            setBuildStatus("Complete","FAILURE","${MERGE_COMMIT}")
+            script {
+                if(params.MERGE_COMMIT){
+                    setBuildStatus("Complete","FAILURE","${MERGE_COMMIT}")
+                }
+            }
         }
         always {
             echo 'Cleanup workspace'
diff --git a/buildenv/jenkins/jobs/builds/Build-linux_x86-64 b/buildenv/jenkins/jobs/builds/Build-linux_x86-64
--- a/buildenv/jenkins/jobs/builds/Build-linux_x86-64
+++ b/buildenv/jenkins/jobs/builds/Build-linux_x86-64
@@ -11,8 +11,12 @@ def setBuildStatus(String message, String state, String sha) {
     ]);
 }
 
+LABEL = (params.LABEL) ? "${params.LABEL}" : "Linux && x86"
+REPO = (params.OMR_REPO) ? "${params.OMR_REPO}" : "https://github.com/eclipse/omr.git"
+BRANCH = (params.OMR_BRANCH) ? "${params.OMR_BRANCH}" : ((params.MERGE_COMMIT) ? "${MERGE_COMMIT}" : "refs/heads/master")
+
 pipeline {
-    agent{label 'Linux && x86'}
+    agent{label "${LABEL}"}
     environment {
         PATH = "/usr/lib/ccache/:$PATH"
     }
@@ -20,9 +24,12 @@ pipeline {
         stage('Get Sources') {
             steps {
                 timestamps {
-                    checkout([$class: 'GitSCM', branches: [[name: '${MERGE_COMMIT}']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/eclipse/omr.git']]])
-                    
-                    setBuildStatus("In Progress","PENDING","${MERGE_COMMIT}")
+                    checkout([$class: 'GitSCM', branches: [[name: "${BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "${REPO}"]]])
+                    script {
+                        if(params.MERGE_COMMIT){
+                            setBuildStatus("In Progress","PENDING","${MERGE_COMMIT}")
+                        }
+                    }
                 }
             }
         }
@@ -30,8 +37,7 @@ pipeline {
             steps {
                 timestamps {
                     echo 'Output CCACHE stats before running and clear them'
-                    sh '''ccache -s -z'''
-                    
+                    sh '''(ccache --version &>/dev/null && ccache -s -z) || echo "Warning: ccache not found"'''
                     dir('build') {
                         echo 'Configure...'
                         sh '''cmake -Wdev -C../cmake/caches/Travis.cmake ..''' 
@@ -41,7 +47,7 @@ pipeline {
                     }
                     
                     echo 'Output CCACHE stats after running'
-                    sh '''ccache -s'''
+                    sh '''(ccache --version &>/dev/null && ccache -s) || echo "Warning: ccache not found"'''
                 }
             }
         }
@@ -58,10 +64,18 @@ pipeline {
     }
     post {
         success {
-            setBuildStatus("Complete","SUCCESS","${MERGE_COMMIT}")
+            script {
+                if(params.MERGE_COMMIT){
+                    setBuildStatus("Complete","SUCCESS","${MERGE_COMMIT}")
+                }
+            }
         }
         failure {
-            setBuildStatus("Complete","FAILURE","${MERGE_COMMIT}")
+            script {
+                if(params.MERGE_COMMIT){
+                    setBuildStatus("Complete","FAILURE","${MERGE_COMMIT}")
+                }
+            }
         }
         always {
             echo 'Cleanup workspace'
diff --git a/buildenv/jenkins/jobs/builds/Build-osx_x86-64 b/buildenv/jenkins/jobs/builds/Build-osx_x86-64
--- a/buildenv/jenkins/jobs/builds/Build-osx_x86-64
+++ b/buildenv/jenkins/jobs/builds/Build-osx_x86-64
@@ -11,8 +11,12 @@ def setBuildStatus(String message, String state, String sha) {
     ]);
 }
 
+LABEL = (params.LABEL) ? "${params.LABEL}" : "OSX && x86"
+REPO = (params.OMR_REPO) ? "${params.OMR_REPO}" : "https://github.com/eclipse/omr.git"
+BRANCH = (params.OMR_BRANCH) ? "${params.OMR_BRANCH}" : ((params.MERGE_COMMIT) ? "${MERGE_COMMIT}" : "refs/heads/master")
+
 pipeline {
-    agent{label 'OSX && x86'}
+    agent{label "${LABEL}"}
     environment {
         GTEST_FILTER = "-*dump_test_create_dump_*:*NumaSetAffinity:*NumaSetAffinitySuspended:*DeathTest*"
         PATH = "/usr/local/opt/ccache/libexec:$PATH"
@@ -21,9 +25,12 @@ pipeline {
         stage('Get Sources') {
             steps {
                 timestamps {
-                    checkout([$class: 'GitSCM', branches: [[name: '${MERGE_COMMIT}']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/eclipse/omr.git']]])
-                    
-                    setBuildStatus("In Progress","PENDING","${MERGE_COMMIT}")
+                    checkout([$class: 'GitSCM', branches: [[name: "${BRANCH}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: "${REPO}"]]])
+                    script {
+                        if(params.MERGE_COMMIT){
+                            setBuildStatus("In Progress","PENDING","${MERGE_COMMIT}")
+                        }
+                    }
                 }
             }
         }
@@ -31,7 +38,7 @@ pipeline {
             steps {
                 timestamps {
                     echo 'Output CCACHE stats before running and clear them'
-                    sh '''ccache -s -z'''
+                    sh '''(ccache --version &>/dev/null && ccache -s -z) || echo "Warning: ccache not found"'''
                     
                     dir('build') {
                         echo 'Configure...'
@@ -42,7 +49,7 @@ pipeline {
                     }
                     
                     echo 'Output CCACHE stats after running'
-                    sh '''ccache -s'''
+                    sh '''(ccache --version &>/dev/null && ccache -s) || echo "Warning: ccache not found"'''
                 }
             }
         }
@@ -59,10 +66,18 @@ pipeline {
     }
     post {
         success {
-            setBuildStatus("Complete","SUCCESS","${MERGE_COMMIT}")
+            script {
+                if(params.MERGE_COMMIT){
+                    setBuildStatus("Complete","SUCCESS","${MERGE_COMMIT}")
+                }
+            }
         }
         failure {
-            setBuildStatus("Complete","FAILURE","${MERGE_COMMIT}")
+            script {
+                if(params.MERGE_COMMIT){
+                    setBuildStatus("Complete","FAILURE","${MERGE_COMMIT}")
+                }
+            }
         }
         always {
             echo 'Cleanup workspace'
